[tool.black]
line-length = 88
target-version = ["py38"]

[tool.ruff]
select = ["E", "F", "I"]
ignore = ["E501", "F722"]

line-length = 88
target-version = "py38"
ignore-init-module-imports = true

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.pycodestyle]
max-doc-length = 400

[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403", "F811"]

[tool.pytest.ini_options]
pythonpath = ["."]
log_cli = true
log_cli_level = "INFO"