# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xservice.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0exservice.proto"\x1b\n\x0cTweetRequest\x12\x0b\n\x03url\x18\x01 \x01(\t"&\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t"E\n\rTweetResponse\x12\x1a\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x06.ErrorH\x00\x88\x01\x01\x12\x0e\n\x06tweets\x18\x02 \x03(\x0c\x42\x08\n\x06_error29\n\x08XService\x12-\n\nFetchTweet\x12\r.TweetRequest\x1a\x0e.TweetResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "xservice_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_TWEETREQUEST"]._serialized_start = 18
    _globals["_TWEETREQUEST"]._serialized_end = 45
    _globals["_ERROR"]._serialized_start = 47
    _globals["_ERROR"]._serialized_end = 85
    _globals["_TWEETRESPONSE"]._serialized_start = 87
    _globals["_TWEETRESPONSE"]._serialized_end = 156
    _globals["_XSERVICE"]._serialized_start = 158
    _globals["_XSERVICE"]._serialized_end = 215
# @@protoc_insertion_point(module_scope)
